export type CategoryLevel = 1 | 2 | 3;

export interface Category {
  id: string;
  name: string;
  nameHi: string;
  slug: string;
  icon: string;
  level: CategoryLevel;
  parentId: string | null;
  displayOrder: number;
  isActive: boolean;
  isOccasion?: boolean;
}

export const CATEGORIES: Category[] = [
  // ─────────────────────────────────────────
  // LEVEL 1
  // ─────────────────────────────────────────
  {
    id: 'women',
    name: 'Women',
    nameHi: 'महिला',
    slug: 'women',
    icon: '',
    level: 1,
    parentId: null,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'men',
    name: 'Men',
    nameHi: 'पुरुष',
    slug: 'men',
    icon: '',
    level: 1,
    parentId: null,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'kids',
    name: 'Kids',
    nameHi: 'बच्चे',
    slug: 'kids',
    icon: '',
    level: 1,
    parentId: null,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'accessories',
    name: 'Accessories',
    nameHi: 'एक्सेसरीज़',
    slug: 'accessories',
    icon: '',
    level: 1,
    parentId: null,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'occasion',
    name: 'Occasion Shop',
    nameHi: 'अवसर शॉप',
    slug: 'occasion',
    icon: '',
    level: 1,
    parentId: null,
    displayOrder: 5,
    isActive: true,
    isOccasion: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 2 — Women
  // ─────────────────────────────────────────
  {
    id: 'sarees',
    name: 'Sarees',
    nameHi: 'साड़ियाँ',
    slug: 'women-sarees',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'kurtis',
    name: 'Kurtis & Kurta Sets',
    nameHi: 'कुर्ती सेट',
    slug: 'women-kurtis',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'salwar-suits',
    name: 'Salwar Suits',
    nameHi: 'सलवार सूट',
    slug: 'women-salwar-suits',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'lehengas',
    name: 'Lehengas',
    nameHi: 'लहंगे',
    slug: 'women-lehengas',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'dress-materials',
    name: 'Dress Materials',
    nameHi: 'ड्रेस मटेरियल',
    slug: 'women-dress-materials',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'blouses',
    name: 'Blouses',
    nameHi: 'ब्लाउज',
    slug: 'women-blouses',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'dupattas',
    name: 'Dupattas & Stoles',
    nameHi: 'दुपट्टे',
    slug: 'women-dupattas',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'western-wear',
    name: 'Western Wear',
    nameHi: 'वेस्टर्न वियर',
    slug: 'women-western-wear',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'bottom-wear',
    name: 'Bottom Wear',
    nameHi: 'बॉटम वियर',
    slug: 'women-bottom-wear',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'innerwear',
    name: 'Innerwear & Loungewear',
    nameHi: 'इनरवियर',
    slug: 'women-innerwear',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 10,
    isActive: true,
  },
  {
    id: 'winter-wear',
    name: 'Winter Wear',
    nameHi: 'विंटर वियर',
    slug: 'women-winter-wear',
    icon: '',
    level: 2,
    parentId: 'women',
    displayOrder: 11,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 2 — Men
  // ─────────────────────────────────────────
  {
    id: 'mens-ethnic',
    name: 'Ethnic Wear',
    nameHi: 'एथनिक वियर',
    slug: 'men-ethnic',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-top',
    name: 'Top Wear',
    nameHi: 'टॉप वियर',
    slug: 'men-top',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'mens-bottom',
    name: 'Bottom Wear',
    nameHi: 'बॉटम वियर',
    slug: 'men-bottom',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'mens-innerwear',
    name: 'Innerwear',
    nameHi: 'इनरवियर',
    slug: 'men-innerwear',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'mens-sports',
    name: 'Sports & Active Wear',
    nameHi: 'स्पोर्ट्स वियर',
    slug: 'men-sports',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'mens-winter',
    name: 'Winter Wear',
    nameHi: 'विंटर वियर',
    slug: 'men-winter',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'mens-nightwear',
    name: 'Night Wear',
    nameHi: 'नाइट वियर',
    slug: 'men-nightwear',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'mens-footwear',
    name: 'Footwear',
    nameHi: 'फुटवियर',
    slug: 'men-footwear',
    icon: '',
    level: 2,
    parentId: 'men',
    displayOrder: 8,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 2 — Kids
  // ─────────────────────────────────────────
  {
    id: 'girls',
    name: 'Girls (2-14 yrs)',
    nameHi: 'लड़कियाँ',
    slug: 'kids-girls',
    icon: '',
    level: 2,
    parentId: 'kids',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'boys',
    name: 'Boys (2-14 yrs)',
    nameHi: 'लड़के',
    slug: 'kids-boys',
    icon: '',
    level: 2,
    parentId: 'kids',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'infant',
    name: 'Infant (0-2 yrs)',
    nameHi: 'शिशु',
    slug: 'kids-infant',
    icon: '',
    level: 2,
    parentId: 'kids',
    displayOrder: 3,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 2 — Accessories
  // ─────────────────────────────────────────
  {
    id: 'jewellery',
    name: 'Jewellery',
    nameHi: 'ज्वेलरी',
    slug: 'accessories-jewellery',
    icon: '',
    level: 2,
    parentId: 'accessories',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'bags',
    name: 'Bags & Clutches',
    nameHi: 'बैग्स',
    slug: 'accessories-bags',
    icon: '',
    level: 2,
    parentId: 'accessories',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'acc-footwear',
    name: 'Footwear',
    nameHi: 'फुटवियर',
    slug: 'accessories-footwear',
    icon: '',
    level: 2,
    parentId: 'accessories',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'watches',
    name: 'Watches',
    nameHi: 'घड़ियाँ',
    slug: 'accessories-watches',
    icon: '⌚',
    level: 2,
    parentId: 'accessories',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'acc-others',
    name: 'Others',
    nameHi: 'अन्य',
    slug: 'accessories-others',
    icon: '',
    level: 2,
    parentId: 'accessories',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 2 — Occasion
  // ─────────────────────────────────────────
  {
    id: 'wedding',
    name: 'Wedding Collection',
    nameHi: 'वेडिंग कलेक्शन',
    slug: 'occasion-wedding',
    icon: '',
    level: 2,
    parentId: 'occasion',
    displayOrder: 1,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'festival',
    name: 'Festival Collection',
    nameHi: 'फेस्टिवल कलेक्शन',
    slug: 'occasion-festival',
    icon: '',
    level: 2,
    parentId: 'occasion',
    displayOrder: 2,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'daily',
    name: 'Daily Wear',
    nameHi: 'डेली वियर',
    slug: 'occasion-daily',
    icon: '',
    level: 2,
    parentId: 'occasion',
    displayOrder: 3,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'party',
    name: 'Party Wear',
    nameHi: 'पार्टी वियर',
    slug: 'occasion-party',
    icon: '',
    level: 2,
    parentId: 'occasion',
    displayOrder: 4,
    isActive: true,
    isOccasion: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Sarees
  // ─────────────────────────────────────────
  {
    id: 'silk-sarees',
    name: 'Silk Sarees',
    nameHi: 'सिल्क साड़ियाँ',
    slug: 'women-sarees-silk',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'cotton-sarees',
    name: 'Cotton Sarees',
    nameHi: 'कॉटन साड़ियाँ',
    slug: 'women-sarees-cotton',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'georgette-sarees',
    name: 'Georgette Sarees',
    nameHi: 'जॉर्जेट साड़ियाँ',
    slug: 'women-sarees-georgette',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'banarasi-sarees',
    name: 'Banarasi Sarees',
    nameHi: 'बनारसी साड़ियाँ',
    slug: 'women-sarees-banarasi',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'chiffon-sarees',
    name: 'Chiffon Sarees',
    nameHi: 'शिफॉन साड़ियाँ',
    slug: 'women-sarees-chiffon',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'printed-sarees',
    name: 'Printed Sarees',
    nameHi: 'प्रिंटेड साड़ियाँ',
    slug: 'women-sarees-printed',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'embroidered-sarees',
    name: 'Embroidered Sarees',
    nameHi: 'कढ़ाई साड़ियाँ',
    slug: 'women-sarees-embroidered',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'designer-sarees',
    name: 'Designer Sarees',
    nameHi: 'डिज़ाइनर साड़ियाँ',
    slug: 'women-sarees-designer',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'daily-wear-sarees',
    name: 'Daily Wear Sarees',
    nameHi: 'डेली वेयर साड़ियाँ',
    slug: 'women-sarees-daily-wear',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'party-wear-sarees',
    name: 'Party Wear Sarees',
    nameHi: 'पार्टी वेयर साड़ियाँ',
    slug: 'women-sarees-party-wear',
    icon: '',
    level: 3,
    parentId: 'sarees',
    displayOrder: 10,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Kurtis
  // ─────────────────────────────────────────
  {
    id: 'straight-kurtis',
    name: 'Straight Kurtis',
    nameHi: 'स्ट्रेट कुर्ती',
    slug: 'women-kurtis-straight',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'anarkali-kurtis',
    name: 'Anarkali Kurtis',
    nameHi: 'अनारकली कुर्ती',
    slug: 'women-kurtis-anarkali',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'aline-kurtis',
    name: 'A-Line Kurtis',
    nameHi: 'ए-लाइन कुर्ती',
    slug: 'women-kurtis-aline',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'kurti-palazzo',
    name: 'Kurti with Palazzo',
    nameHi: 'कुर्ती पलाज़ो',
    slug: 'women-kurtis-palazzo',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'kurti-pant',
    name: 'Kurti with Pant',
    nameHi: 'कुर्ती पैंट',
    slug: 'women-kurtis-pant',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'kurti-dupatta',
    name: 'Kurti with Dupatta',
    nameHi: 'कुर्ती दुपट्टा',
    slug: 'women-kurtis-dupatta',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'kurti-set-3pc',
    name: '3-Piece Kurti Set',
    nameHi: '3 पीस कुर्ती सेट',
    slug: 'women-kurtis-3pc',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'short-kurtis',
    name: 'Short Kurtis',
    nameHi: 'शॉर्ट कुर्ती',
    slug: 'women-kurtis-short',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'long-kurtis',
    name: 'Long Kurtis',
    nameHi: 'लॉन्ग कुर्ती',
    slug: 'women-kurtis-long',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'embroidered-kurtis',
    name: 'Embroidered Kurtis',
    nameHi: 'कढ़ाई कुर्ती',
    slug: 'women-kurtis-embroidered',
    icon: '',
    level: 3,
    parentId: 'kurtis',
    displayOrder: 10,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Salwar Suits
  // ─────────────────────────────────────────
  {
    id: 'churidar-suits',
    name: 'Churidar Suits',
    nameHi: 'चूड़ीदार सूट',
    slug: 'women-salwar-suits-churidar',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'patiala-suits',
    name: 'Patiala Suits',
    nameHi: 'पटियाला सूट',
    slug: 'women-salwar-suits-patiala',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'anarkali-suits',
    name: 'Anarkali Suits',
    nameHi: 'अनारकली सूट',
    slug: 'women-salwar-suits-anarkali',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'pakistani-suits',
    name: 'Pakistani Suits',
    nameHi: 'पाकिस्तानी सूट',
    slug: 'women-salwar-suits-pakistani',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'unstitched-suits',
    name: 'Unstitched Suits',
    nameHi: 'अनस्टिच्ड सूट',
    slug: 'women-salwar-suits-unstitched',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'semi-stitched-suits',
    name: 'Semi-Stitched Suits',
    nameHi: 'सेमी स्टिच्ड सूट',
    slug: 'women-salwar-suits-semi-stitched',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'readymade-suits',
    name: 'Readymade Suits',
    nameHi: 'रेडीमेड सूट',
    slug: 'women-salwar-suits-readymade',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'cotton-suits',
    name: 'Cotton Suits',
    nameHi: 'कॉटन सूट',
    slug: 'women-salwar-suits-cotton',
    icon: '',
    level: 3,
    parentId: 'salwar-suits',
    displayOrder: 8,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Lehengas
  // ─────────────────────────────────────────
  {
    id: 'bridal-lehengas',
    name: 'Bridal Lehengas',
    nameHi: 'ब्राइडल लहंगा',
    slug: 'women-lehengas-bridal',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'party-lehengas',
    name: 'Party Lehengas',
    nameHi: 'पार्टी लहंगा',
    slug: 'women-lehengas-party',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'festival-lehengas',
    name: 'Festival Lehengas',
    nameHi: 'फेस्टिवल लहंगा',
    slug: 'women-lehengas-festival',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'lehenga-choli',
    name: 'Lehenga Choli',
    nameHi: 'लहंगा चोली',
    slug: 'women-lehengas-choli',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'half-saree',
    name: 'Half Saree',
    nameHi: 'हाफ साड़ी',
    slug: 'women-lehengas-half-saree',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'designer-lehengas',
    name: 'Designer Lehengas',
    nameHi: 'डिज़ाइनर लहंगा',
    slug: 'women-lehengas-designer',
    icon: '',
    level: 3,
    parentId: 'lehengas',
    displayOrder: 6,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Dress Materials
  // ─────────────────────────────────────────
  {
    id: 'cotton-dress-materials',
    name: 'Cotton Dress Materials',
    nameHi: 'कॉटन ड्रेस मटेरियल',
    slug: 'women-dress-materials-cotton',
    icon: '',
    level: 3,
    parentId: 'dress-materials',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'silk-dress-materials',
    name: 'Silk Dress Materials',
    nameHi: 'सिल्क ड्रेस मटेरियल',
    slug: 'women-dress-materials-silk',
    icon: '',
    level: 3,
    parentId: 'dress-materials',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'embroidered-dress-materials',
    name: 'Embroidered Dress Materials',
    nameHi: 'कढ़ाई ड्रेस मटेरियल',
    slug: 'women-dress-materials-embroidered',
    icon: '',
    level: 3,
    parentId: 'dress-materials',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'printed-dress-materials',
    name: 'Printed Dress Materials',
    nameHi: 'प्रिंटेड ड्रेस मटेरियल',
    slug: 'women-dress-materials-printed',
    icon: '',
    level: 3,
    parentId: 'dress-materials',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Blouses
  // ─────────────────────────────────────────
  {
    id: 'readymade-blouses',
    name: 'Readymade Blouses',
    nameHi: 'रेडीमेड ब्लाउज',
    slug: 'women-blouses-readymade',
    icon: '',
    level: 3,
    parentId: 'blouses',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'embroidered-blouses',
    name: 'Embroidered Blouses',
    nameHi: 'कढ़ाई ब्लाउज',
    slug: 'women-blouses-embroidered',
    icon: '',
    level: 3,
    parentId: 'blouses',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'designer-blouses',
    name: 'Designer Blouses',
    nameHi: 'डिज़ाइनर ब्लाउज',
    slug: 'women-blouses-designer',
    icon: '',
    level: 3,
    parentId: 'blouses',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'unstitched-blouses',
    name: 'Blouse Pieces',
    nameHi: 'ब्लाउज पीस',
    slug: 'women-blouses-pieces',
    icon: '',
    level: 3,
    parentId: 'blouses',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Dupattas
  // ─────────────────────────────────────────
  {
    id: 'silk-dupattas',
    name: 'Silk Dupattas',
    nameHi: 'सिल्क दुपट्टा',
    slug: 'women-dupattas-silk',
    icon: '',
    level: 3,
    parentId: 'dupattas',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'printed-dupattas',
    name: 'Printed Dupattas',
    nameHi: 'प्रिंटेड दुपट्टा',
    slug: 'women-dupattas-printed',
    icon: '',
    level: 3,
    parentId: 'dupattas',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'embroidered-dupattas',
    name: 'Embroidered Dupattas',
    nameHi: 'कढ़ाई दुपट्टा',
    slug: 'women-dupattas-embroidered',
    icon: '',
    level: 3,
    parentId: 'dupattas',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'stoles',
    name: 'Stoles & Scarves',
    nameHi: 'स्टोल और स्कार्फ',
    slug: 'women-dupattas-stoles',
    icon: '',
    level: 3,
    parentId: 'dupattas',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Western Wear (Women)
  // ─────────────────────────────────────────
  {
    id: 'western-tops',
    name: 'Tops & T-Shirts',
    nameHi: 'टॉप्स और टी-शर्ट',
    slug: 'women-western-tops',
    icon: '',
    level: 3,
    parentId: 'western-wear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'western-dresses',
    name: 'Dresses & Jumpsuits',
    nameHi: 'ड्रेसेज़ और जम्पसूट',
    slug: 'women-western-dresses',
    icon: '',
    level: 3,
    parentId: 'western-wear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'western-jeans',
    name: 'Jeans & Jeggings',
    nameHi: 'जींस और जेगिंग्स',
    slug: 'women-western-jeans',
    icon: '',
    level: 3,
    parentId: 'western-wear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'western-skirts',
    name: 'Skirts',
    nameHi: 'स्कर्ट',
    slug: 'women-western-skirts',
    icon: '',
    level: 3,
    parentId: 'western-wear',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'western-co-ords',
    name: 'Co-ord Sets',
    nameHi: 'को-ऑर्ड सेट',
    slug: 'women-western-coords',
    icon: '',
    level: 3,
    parentId: 'western-wear',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Bottom Wear (Women)
  // ─────────────────────────────────────────
  {
    id: 'leggings',
    name: 'Leggings',
    nameHi: 'लेगिंग्स',
    slug: 'women-bottom-leggings',
    icon: '',
    level: 3,
    parentId: 'bottom-wear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'palazzos',
    name: 'Palazzos',
    nameHi: 'पलाज़ो',
    slug: 'women-bottom-palazzos',
    icon: '',
    level: 3,
    parentId: 'bottom-wear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'churidars',
    name: 'Churidars',
    nameHi: 'चूड़ीदार',
    slug: 'women-bottom-churidars',
    icon: '',
    level: 3,
    parentId: 'bottom-wear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'patialas',
    name: 'Patialas',
    nameHi: 'पटियाला',
    slug: 'women-bottom-patialas',
    icon: '',
    level: 3,
    parentId: 'bottom-wear',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'skirts-bottom',
    name: 'Skirts',
    nameHi: 'स्कर्ट',
    slug: 'women-bottom-skirts',
    icon: '',
    level: 3,
    parentId: 'bottom-wear',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Innerwear (Women)
  // ─────────────────────────────────────────
  {
    id: 'womens-bras',
    name: 'Bras',
    nameHi: 'ब्रा',
    slug: 'women-innerwear-bras',
    icon: '',
    level: 3,
    parentId: 'innerwear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'womens-briefs',
    name: 'Briefs & Panties',
    nameHi: 'ब्रीफ और पैंटी',
    slug: 'women-innerwear-briefs',
    icon: '',
    level: 3,
    parentId: 'innerwear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'womens-nightwear',
    name: 'Nightwear & Loungewear',
    nameHi: 'नाइटवियर',
    slug: 'women-innerwear-nightwear',
    icon: '',
    level: 3,
    parentId: 'innerwear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'womens-shapewear',
    name: 'Shapewear',
    nameHi: 'शेपवियर',
    slug: 'women-innerwear-shapewear',
    icon: '',
    level: 3,
    parentId: 'innerwear',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Winter Wear (Women)
  // ─────────────────────────────────────────
  {
    id: 'womens-sweaters',
    name: 'Sweaters',
    nameHi: 'स्वेटर',
    slug: 'women-winter-sweaters',
    icon: '',
    level: 3,
    parentId: 'winter-wear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'womens-jackets',
    name: 'Jackets & Coats',
    nameHi: 'जैकेट और कोट',
    slug: 'women-winter-jackets',
    icon: '',
    level: 3,
    parentId: 'winter-wear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'womens-shawls',
    name: 'Shawls & Wraps',
    nameHi: 'शॉल और रैप',
    slug: 'women-winter-shawls',
    icon: '',
    level: 3,
    parentId: 'winter-wear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'womens-hoodies',
    name: 'Hoodies & Sweatshirts',
    nameHi: 'हूडी और स्वेटशर्ट',
    slug: 'women-winter-hoodies',
    icon: '',
    level: 3,
    parentId: 'winter-wear',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Ethnic
  // ─────────────────────────────────────────
  {
    id: 'kurtas',
    name: 'Kurtas',
    nameHi: 'कुर्ता',
    slug: 'men-ethnic-kurtas',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'kurta-pajama',
    name: 'Kurta Pajama Sets',
    nameHi: 'कुर्ता पजामा',
    slug: 'men-ethnic-kurta-pajama',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'nehru-jackets',
    name: 'Nehru Jackets',
    nameHi: 'नेहरू जैकेट',
    slug: 'men-ethnic-nehru-jackets',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'sherwanis',
    name: 'Sherwanis',
    nameHi: 'शेरवानी',
    slug: 'men-ethnic-sherwanis',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'dhotis-lungis',
    name: 'Dhotis & Lungis',
    nameHi: 'धोती और लुंगी',
    slug: 'men-ethnic-dhotis',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'pathani-suits',
    name: 'Pathani Suits',
    nameHi: 'पठानी सूट',
    slug: 'men-ethnic-pathani',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'mens-ethnic-sets',
    name: 'Ethnic Sets',
    nameHi: 'एथनिक सेट',
    slug: 'men-ethnic-sets',
    icon: '',
    level: 3,
    parentId: 'mens-ethnic',
    displayOrder: 7,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Top Wear
  // ─────────────────────────────────────────
  {
    id: 'mens-tshirts',
    name: 'T-Shirts',
    nameHi: 'टी-शर्ट',
    slug: 'men-top-tshirts',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'casual-shirts',
    name: 'Casual Shirts',
    nameHi: 'कैजुअल शर्ट',
    slug: 'men-top-casual-shirts',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'formal-shirts',
    name: 'Formal Shirts',
    nameHi: 'फॉर्मल शर्ट',
    slug: 'men-top-formal-shirts',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'polo-tshirts',
    name: 'Polo T-Shirts',
    nameHi: 'पोलो टी-शर्ट',
    slug: 'men-top-polo',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'oversized-tshirts',
    name: 'Oversized T-Shirts',
    nameHi: 'ओवरसाइज़ड टी-शर्ट',
    slug: 'men-top-oversized',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'tshirt-combos',
    name: 'T-Shirt Combos',
    nameHi: 'टी-शर्ट कॉम्बो',
    slug: 'men-top-combos',
    icon: '',
    level: 3,
    parentId: 'mens-top',
    displayOrder: 6,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Bottom Wear
  // ─────────────────────────────────────────
  {
    id: 'mens-jeans',
    name: 'Jeans',
    nameHi: 'जींस',
    slug: 'men-bottom-jeans',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'casual-trousers',
    name: 'Casual Trousers',
    nameHi: 'कैजुअल ट्राउज़र',
    slug: 'men-bottom-casual-trousers',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'formal-trousers',
    name: 'Formal Trousers',
    nameHi: 'फॉर्मल ट्राउज़र',
    slug: 'men-bottom-formal-trousers',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'cargo-pants',
    name: 'Cargo Pants',
    nameHi: 'कार्गो पैंट',
    slug: 'men-bottom-cargo',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'track-pants',
    name: 'Track Pants',
    nameHi: 'ट्रैक पैंट',
    slug: 'men-bottom-track',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'shorts',
    name: 'Shorts',
    nameHi: 'शॉर्ट्स',
    slug: 'men-bottom-shorts',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'joggers',
    name: 'Joggers',
    nameHi: 'जॉगर्स',
    slug: 'men-bottom-joggers',
    icon: '',
    level: 3,
    parentId: 'mens-bottom',
    displayOrder: 7,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Innerwear
  // ─────────────────────────────────────────
  {
    id: 'mens-vests',
    name: 'Vests & Undershirts',
    nameHi: 'बनियान',
    slug: 'men-innerwear-vests',
    icon: '',
    level: 3,
    parentId: 'mens-innerwear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-briefs',
    name: 'Briefs & Trunks',
    nameHi: 'ब्रीफ और ट्रंक',
    slug: 'men-innerwear-briefs',
    icon: '',
    level: 3,
    parentId: 'mens-innerwear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'mens-boxers',
    name: 'Boxers',
    nameHi: 'बॉक्सर',
    slug: 'men-innerwear-boxers',
    icon: '',
    level: 3,
    parentId: 'mens-innerwear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'mens-thermal',
    name: 'Thermal Wear',
    nameHi: 'थर्मल वियर',
    slug: 'men-innerwear-thermal',
    icon: '',
    level: 3,
    parentId: 'mens-innerwear',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Sports
  // ─────────────────────────────────────────
  {
    id: 'sports-tshirts',
    name: 'Sports T-Shirts',
    nameHi: 'स्पोर्ट्स टी-शर्ट',
    slug: 'men-sports-tshirts',
    icon: '',
    level: 3,
    parentId: 'mens-sports',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sports-shorts',
    name: 'Sports Shorts',
    nameHi: 'स्पोर्ट्स शॉर्ट्स',
    slug: 'men-sports-shorts',
    icon: '',
    level: 3,
    parentId: 'mens-sports',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sports-track-suits',
    name: 'Track Suits',
    nameHi: 'ट्रैक सूट',
    slug: 'men-sports-track-suits',
    icon: '',
    level: 3,
    parentId: 'mens-sports',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'gym-wear',
    name: 'Gym Wear',
    nameHi: 'जिम वियर',
    slug: 'men-sports-gym',
    icon: '',
    level: 3,
    parentId: 'mens-sports',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Winter
  // ─────────────────────────────────────────
  {
    id: 'mens-sweaters',
    name: 'Sweaters',
    nameHi: 'स्वेटर',
    slug: 'men-winter-sweaters',
    icon: '',
    level: 3,
    parentId: 'mens-winter',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-jackets',
    name: 'Jackets',
    nameHi: 'जैकेट',
    slug: 'men-winter-jackets',
    icon: '',
    level: 3,
    parentId: 'mens-winter',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'mens-hoodies',
    name: 'Hoodies & Sweatshirts',
    nameHi: 'हूडी और स्वेटशर्ट',
    slug: 'men-winter-hoodies',
    icon: '',
    level: 3,
    parentId: 'mens-winter',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'mens-blazers',
    name: 'Blazers',
    nameHi: 'ब्लेज़र',
    slug: 'men-winter-blazers',
    icon: '',
    level: 3,
    parentId: 'mens-winter',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Nightwear
  // ─────────────────────────────────────────
  {
    id: 'mens-pyjamas',
    name: 'Pyjamas',
    nameHi: 'पजामा',
    slug: 'men-nightwear-pyjamas',
    icon: '',
    level: 3,
    parentId: 'mens-nightwear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-night-suits',
    name: 'Night Suits',
    nameHi: 'नाइट सूट',
    slug: 'men-nightwear-suits',
    icon: '',
    level: 3,
    parentId: 'mens-nightwear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'mens-lounge-pants',
    name: 'Lounge Pants',
    nameHi: 'लाउंज पैंट',
    slug: 'men-nightwear-lounge',
    icon: '',
    level: 3,
    parentId: 'mens-nightwear',
    displayOrder: 3,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Men Footwear
  // ─────────────────────────────────────────
  {
    id: 'mens-casual-shoes',
    name: 'Casual Shoes',
    nameHi: 'कैजुअल जूते',
    slug: 'men-footwear-casual',
    icon: '',
    level: 3,
    parentId: 'mens-footwear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-formal-shoes',
    name: 'Formal Shoes',
    nameHi: 'फॉर्मल जूते',
    slug: 'men-footwear-formal',
    icon: '',
    level: 3,
    parentId: 'mens-footwear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'mens-sandals',
    name: 'Sandals & Slippers',
    nameHi: 'सैंडल और चप्पल',
    slug: 'men-footwear-sandals',
    icon: '',
    level: 3,
    parentId: 'mens-footwear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'mens-sports-shoes',
    name: 'Sports Shoes',
    nameHi: 'स्पोर्ट्स जूते',
    slug: 'men-footwear-sports',
    icon: '',
    level: 3,
    parentId: 'mens-footwear',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'kolhapuri',
    name: 'Ethnic & Kolhapuri',
    nameHi: 'एथनिक और कोल्हापुरी',
    slug: 'men-footwear-ethnic',
    icon: '',
    level: 3,
    parentId: 'mens-footwear',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Girls
  // ─────────────────────────────────────────
  {
    id: 'girls-ethnic',
    name: 'Ethnic Wear',
    nameHi: 'एथनिक वियर',
    slug: 'kids-girls-ethnic',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'girls-dresses',
    name: 'Dresses & Frocks',
    nameHi: 'फ्रॉक और ड्रेसेज़',
    slug: 'kids-girls-dresses',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'girls-tops',
    name: 'Tops & T-Shirts',
    nameHi: 'टॉप्स और टी-शर्ट',
    slug: 'kids-girls-tops',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'girls-pants',
    name: 'Pants & Leggings',
    nameHi: 'पैंट और लेगिंग्स',
    slug: 'kids-girls-pants',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'girls-sets',
    name: 'Co-ord Sets',
    nameHi: 'को-ऑर्ड सेट',
    slug: 'kids-girls-sets',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'girls-party',
    name: 'Party Wear',
    nameHi: 'पार्टी वियर',
    slug: 'kids-girls-party',
    icon: '',
    level: 3,
    parentId: 'girls',
    displayOrder: 6,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Boys
  // ─────────────────────────────────────────
  {
    id: 'boys-ethnic',
    name: 'Ethnic Wear',
    nameHi: 'एथनिक वियर',
    slug: 'kids-boys-ethnic',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'boys-tshirts',
    name: 'T-Shirts',
    nameHi: 'टी-शर्ट',
    slug: 'kids-boys-tshirts',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'boys-pants',
    name: 'Pants & Jeans',
    nameHi: 'पैंट और जींस',
    slug: 'kids-boys-pants',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'boys-sets',
    name: 'Sets & Combos',
    nameHi: 'सेट और कॉम्बो',
    slug: 'kids-boys-sets',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'boys-party',
    name: 'Party Wear',
    nameHi: 'पार्टी वियर',
    slug: 'kids-boys-party',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'boys-winter',
    name: 'Winter Wear',
    nameHi: 'विंटर वियर',
    slug: 'kids-boys-winter',
    icon: '',
    level: 3,
    parentId: 'boys',
    displayOrder: 6,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Infant
  // ─────────────────────────────────────────
  {
    id: 'infant-bodysuits',
    name: 'Bodysuits & Rompers',
    nameHi: 'बॉडीसूट और रॉम्पर',
    slug: 'kids-infant-bodysuits',
    icon: '',
    level: 3,
    parentId: 'infant',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'infant-sets',
    name: 'Clothing Sets',
    nameHi: 'कपड़े सेट',
    slug: 'kids-infant-sets',
    icon: '',
    level: 3,
    parentId: 'infant',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'infant-ethnic',
    name: 'Ethnic Wear',
    nameHi: 'एथनिक वियर',
    slug: 'kids-infant-ethnic',
    icon: '',
    level: 3,
    parentId: 'infant',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'infant-winter',
    name: 'Winter Wear',
    nameHi: 'विंटर वियर',
    slug: 'kids-infant-winter',
    icon: '',
    level: 3,
    parentId: 'infant',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Jewellery
  // ─────────────────────────────────────────
  {
    id: 'necklace-sets',
    name: 'Necklace Sets',
    nameHi: 'नेकलेस सेट',
    slug: 'accessories-jewellery-necklace',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'earrings',
    name: 'Earrings',
    nameHi: 'झुमके और इयररिंग',
    slug: 'accessories-jewellery-earrings',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'bangles-bracelets',
    name: 'Bangles & Bracelets',
    nameHi: 'चूड़ियाँ और ब्रेसलेट',
    slug: 'accessories-jewellery-bangles',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'anklets',
    name: 'Anklets',
    nameHi: 'पायल',
    slug: 'accessories-jewellery-anklets',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'maang-tikka',
    name: 'Maang Tikka',
    nameHi: 'माँग टीका',
    slug: 'accessories-jewellery-maang-tikka',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'nose-rings',
    name: 'Nose Rings',
    nameHi: 'नथ',
    slug: 'accessories-jewellery-nose-rings',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'rings',
    name: 'Rings',
    nameHi: 'अंगूठी',
    slug: 'accessories-jewellery-rings',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'bridal-jewellery',
    name: 'Bridal Jewellery Sets',
    nameHi: 'ब्राइडल ज्वेलरी',
    slug: 'accessories-jewellery-bridal',
    icon: '',
    level: 3,
    parentId: 'jewellery',
    displayOrder: 8,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Bags
  // ─────────────────────────────────────────
  {
    id: 'handbags',
    name: 'Handbags',
    nameHi: 'हैंडबैग',
    slug: 'accessories-bags-handbags',
    icon: '',
    level: 3,
    parentId: 'bags',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'clutches',
    name: 'Clutches',
    nameHi: 'क्लच',
    slug: 'accessories-bags-clutches',
    icon: '',
    level: 3,
    parentId: 'bags',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'tote-bags',
    name: 'Tote Bags',
    nameHi: 'टोट बैग',
    slug: 'accessories-bags-totes',
    icon: '',
    level: 3,
    parentId: 'bags',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'backpacks',
    name: 'Backpacks',
    nameHi: 'बैकपैक',
    slug: 'accessories-bags-backpacks',
    icon: '',
    level: 3,
    parentId: 'bags',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'potli-bags',
    name: 'Potli Bags',
    nameHi: 'पोटली बैग',
    slug: 'accessories-bags-potli',
    icon: '',
    level: 3,
    parentId: 'bags',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Accessories Footwear
  // ─────────────────────────────────────────
  {
    id: 'womens-heels',
    name: 'Heels & Pumps',
    nameHi: 'हील्स',
    slug: 'accessories-footwear-heels',
    icon: '',
    level: 3,
    parentId: 'acc-footwear',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'womens-flats',
    name: 'Flats & Ballerinas',
    nameHi: 'फ्लैट्स',
    slug: 'accessories-footwear-flats',
    icon: '',
    level: 3,
    parentId: 'acc-footwear',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'womens-sandals',
    name: 'Sandals & Slippers',
    nameHi: 'सैंडल और चप्पल',
    slug: 'accessories-footwear-sandals',
    icon: '',
    level: 3,
    parentId: 'acc-footwear',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'juttis-kolhapuris',
    name: 'Juttis & Kolhapuris',
    nameHi: 'जूती और कोल्हापुरी',
    slug: 'accessories-footwear-juttis',
    icon: '',
    level: 3,
    parentId: 'acc-footwear',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'womens-boots',
    name: 'Boots & Sneakers',
    nameHi: 'बूट्स और स्नीकर्स',
    slug: 'accessories-footwear-boots',
    icon: '',
    level: 3,
    parentId: 'acc-footwear',
    displayOrder: 5,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Watches
  // ─────────────────────────────────────────
  {
    id: 'womens-watches',
    name: "Women's Watches",
    nameHi: 'महिला घड़ी',
    slug: 'accessories-watches-women',
    icon: '⌚',
    level: 3,
    parentId: 'watches',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'mens-watches',
    name: "Men's Watches",
    nameHi: 'पुरुष घड़ी',
    slug: 'accessories-watches-men',
    icon: '⌚',
    level: 3,
    parentId: 'watches',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'kids-watches',
    name: "Kids' Watches",
    nameHi: 'बच्चों की घड़ी',
    slug: 'accessories-watches-kids',
    icon: '⌚',
    level: 3,
    parentId: 'watches',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'smart-watches',
    name: 'Smart Watches',
    nameHi: 'स्मार्ट वॉच',
    slug: 'accessories-watches-smart',
    icon: '⌚',
    level: 3,
    parentId: 'watches',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Accessories Others
  // ─────────────────────────────────────────
  {
    id: 'hair-accessories',
    name: 'Hair Accessories',
    nameHi: 'बालों की एक्सेसरीज़',
    slug: 'accessories-others-hair',
    icon: '',
    level: 3,
    parentId: 'acc-others',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'belts',
    name: 'Belts',
    nameHi: 'बेल्ट',
    slug: 'accessories-others-belts',
    icon: '',
    level: 3,
    parentId: 'acc-others',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sunglasses',
    name: 'Sunglasses',
    nameHi: 'सनग्लासेस',
    slug: 'accessories-others-sunglasses',
    icon: '',
    level: 3,
    parentId: 'acc-others',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'scarves-acc',
    name: 'Scarves & Mufflers',
    nameHi: 'स्कार्फ और मफलर',
    slug: 'accessories-others-scarves',
    icon: '',
    level: 3,
    parentId: 'acc-others',
    displayOrder: 4,
    isActive: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Wedding (Occasion)
  // ─────────────────────────────────────────
  {
    id: 'bridal-wear',
    name: 'Bridal Wear',
    nameHi: 'ब्राइडल वियर',
    slug: 'occasion-wedding-bridal',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 1,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'groom-wear',
    name: 'Groom Wear',
    nameHi: 'दूल्हे का वियर',
    slug: 'occasion-wedding-groom',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 2,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'wedding-guest-women',
    name: 'Guest Wear (Women)',
    nameHi: 'महिला गेस्ट वियर',
    slug: 'occasion-wedding-guest-women',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 3,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'wedding-guest-men',
    name: 'Guest Wear (Men)',
    nameHi: 'पुरुष गेस्ट वियर',
    slug: 'occasion-wedding-guest-men',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 4,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'mehendi-haldi',
    name: 'Mehendi & Haldi',
    nameHi: 'मेहंदी और हल्दी',
    slug: 'occasion-wedding-mehendi',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 5,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'sangeet',
    name: 'Sangeet',
    nameHi: 'संगीत',
    slug: 'occasion-wedding-sangeet',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 6,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'wedding-jewellery',
    name: 'Wedding Jewellery',
    nameHi: 'वेडिंग ज्वेलरी',
    slug: 'occasion-wedding-jewellery',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 7,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'wedding-footwear',
    name: 'Wedding Footwear',
    nameHi: 'वेडिंग फुटवियर',
    slug: 'occasion-wedding-footwear',
    icon: '',
    level: 3,
    parentId: 'wedding',
    displayOrder: 8,
    isActive: true,
    isOccasion: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Festival (Occasion)
  // ─────────────────────────────────────────
  {
    id: 'diwali',
    name: 'Diwali',
    nameHi: 'दिवाली',
    slug: 'occasion-festival-diwali',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 1,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'chhath-puja',
    name: 'Chhath Puja',
    nameHi: 'छठ पूजा',
    slug: 'occasion-festival-chhath',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 2,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'eid',
    name: 'Eid',
    nameHi: 'ईद',
    slug: 'occasion-festival-eid',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 3,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'navratri',
    name: 'Navratri',
    nameHi: 'नवरात्रि',
    slug: 'occasion-festival-navratri',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 4,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'pongal',
    name: 'Pongal',
    nameHi: 'पोंगल',
    slug: 'occasion-festival-pongal',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 5,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'raksha-bandhan',
    name: 'Raksha Bandhan',
    nameHi: 'रक्षाबंधन',
    slug: 'occasion-festival-raksha-bandhan',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 6,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'karwa-chauth',
    name: 'Karwa Chauth',
    nameHi: 'करवाचौथ',
    slug: 'occasion-festival-karwa-chauth',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 7,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'holi',
    name: 'Holi',
    nameHi: 'होली',
    slug: 'occasion-festival-holi',
    icon: '',
    level: 3,
    parentId: 'festival',
    displayOrder: 8,
    isActive: true,
    isOccasion: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Daily Wear (Occasion)
  // ─────────────────────────────────────────
  {
    id: 'daily-casual',
    name: 'Casual Daily',
    nameHi: 'कैजुअल डेली',
    slug: 'occasion-daily-casual',
    icon: '',
    level: 3,
    parentId: 'daily',
    displayOrder: 1,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'daily-office',
    name: 'Office Wear',
    nameHi: 'ऑफिस वियर',
    slug: 'occasion-daily-office',
    icon: '',
    level: 3,
    parentId: 'daily',
    displayOrder: 2,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'daily-college',
    name: 'College/Campus',
    nameHi: 'कॉलेज वियर',
    slug: 'occasion-daily-college',
    icon: '',
    level: 3,
    parentId: 'daily',
    displayOrder: 3,
    isActive: true,
    isOccasion: true,
  },

  // ─────────────────────────────────────────
  // LEVEL 3 — Party Wear (Occasion)
  // ─────────────────────────────────────────
  {
    id: 'party-women',
    name: "Women's Party Wear",
    nameHi: 'महिला पार्टी वियर',
    slug: 'occasion-party-women',
    icon: '',
    level: 3,
    parentId: 'party',
    displayOrder: 1,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'party-men',
    name: "Men's Party Wear",
    nameHi: 'पुरुष पार्टी वियर',
    slug: 'occasion-party-men',
    icon: '',
    level: 3,
    parentId: 'party',
    displayOrder: 2,
    isActive: true,
    isOccasion: true,
  },
  {
    id: 'party-kids',
    name: "Kids' Party Wear",
    nameHi: 'बच्चों का पार्टी वियर',
    slug: 'occasion-party-kids',
    icon: '',
    level: 3,
    parentId: 'party',
    displayOrder: 3,
    isActive: true,
    isOccasion: true,
  },
];

// ─────────────────────────────────────────────────────────
// Helper functions
// ─────────────────────────────────────────────────────────

export function getLevel1Categories(): Category[] {
  return CATEGORIES.filter((c) => c.level === 1 && c.isActive).sort(
    (a, b) => a.displayOrder - b.displayOrder,
  );
}

export function getLevel2Categories(parentId: string): Category[] {
  return CATEGORIES.filter(
    (c) => c.level === 2 && c.parentId === parentId && c.isActive,
  ).sort((a, b) => a.displayOrder - b.displayOrder);
}

export function getLevel3Categories(parentId: string): Category[] {
  return CATEGORIES.filter(
    (c) => c.level === 3 && c.parentId === parentId && c.isActive,
  ).sort((a, b) => a.displayOrder - b.displayOrder);
}

/** Returns the breadcrumb path [L1, L2, L3] for a given category id. */
export function getCategoryPath(categoryId: string): Category[] {
  const category = CATEGORIES.find((c) => c.id === categoryId);
  if (!category) return [];

  if (category.level === 1) return [category];

  if (category.level === 2) {
    const parent = CATEGORIES.find((c) => c.id === category.parentId);
    return parent ? [parent, category] : [category];
  }

  // level 3
  const l2 = CATEGORIES.find((c) => c.id === category.parentId);
  if (!l2) return [category];
  const l1 = CATEGORIES.find((c) => c.id === l2.parentId);
  return l1 ? [l1, l2, category] : [l2, category];
}

/** Search across all L3 categories and return matching triplets. */
export function searchCategories(
  query: string,
): { l1: Category; l2: Category; l3: Category }[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const results: { l1: Category; l2: Category; l3: Category }[] = [];

  const l3Cats = CATEGORIES.filter((c) => c.level === 3 && c.isActive);

  for (const l3 of l3Cats) {
    const matches =
      l3.name.toLowerCase().includes(q) ||
      l3.nameHi.includes(q) ||
      l3.slug.includes(q);

    if (matches) {
      const l2 = CATEGORIES.find((c) => c.id === l3.parentId);
      if (!l2) continue;
      const l1 = CATEGORIES.find((c) => c.id === l2.parentId);
      if (!l1) continue;
      results.push({ l1, l2, l3 });
    }
  }

  return results;
}

// ─────────────────────────────────────────────────────────
// Occasion tags for product tagging (separate from navigation categories)
// ─────────────────────────────────────────────────────────
export const OCCASION_TAGS = [
  { id: 'wedding', label: 'Wedding Season', labelHi: 'वेडिंग सीज़न', icon: '' },
  { id: 'chhath', label: 'Chhath Puja', labelHi: 'छठ पूजा', icon: '' },
  { id: 'diwali', label: 'Diwali', labelHi: 'दिवाली', icon: '' },
  { id: 'eid', label: 'Eid', labelHi: 'ईद', icon: '' },
  { id: 'navratri', label: 'Navratri', labelHi: 'नवरात्रि', icon: '' },
  { id: 'daily-office', label: 'Daily Office', labelHi: 'ऑफिस वियर', icon: '' },
  { id: 'college', label: 'College/Campus', labelHi: 'कॉलेज', icon: '' },
  { id: 'party', label: 'Party Wear', labelHi: 'पार्टी वियर', icon: '' },
  { id: 'anniversary', label: 'Anniversary', labelHi: 'एनिवर्सरी', icon: '' },
  { id: 'mehendi', label: 'Mehendi/Haldi', labelHi: 'मेहंदी/हल्दी', icon: '' },
  { id: 'sangeet', label: 'Sangeet', labelHi: 'संगीत', icon: '' },
  { id: 'raksha-bandhan', label: 'Raksha Bandhan', labelHi: 'रक्षाबंधन', icon: '' },
  { id: 'karwa-chauth', label: 'Karwa Chauth', labelHi: 'करवाचौथ', icon: '' },
  { id: 'holi', label: 'Holi', labelHi: 'होली', icon: '' },
  { id: 'casual', label: 'Casual Everyday', labelHi: 'कैजुअल', icon: '' },
  { id: 'all-occasions', label: 'All Occasions', labelHi: 'सभी अवसर', icon: '' },
];
